from datetime import timedelta
from homeassistant.const import Platform
DOMAIN='garmin_livetrack'
PLATFORMS=[Platform.SENSOR,Platform.BINARY_SENSOR,Platform.DEVICE_TRACKER]
EVENT_IMAP_CONTENT='imap_content'
EVENT_SESSION_ADDED='garmin_livetrack_session_added'
EVENT_SESSION_UPDATED='garmin_livetrack_session_updated'
EVENT_SESSION_ENDED='garmin_livetrack_session_ended'
EVENT_SESSION_REJECTED='garmin_livetrack_session_rejected'
SERVICE_ADD_URL='add_url'
SERVICE_STOP_SESSION='stop_session'
SERVICE_CLEAR_ENDED='clear_ended'
SERVICE_RELOAD_USERS='reload_users'
SERVICE_TEST_NOTIFICATION='test_notification'
CONF_LISTEN_TO_IMAP_EVENTS='listen_to_imap_events'
CONF_ENABLE_NOTIFICATIONS='enable_notifications'
CONF_NOTIFY_SERVICE='notify_service'
CONF_IOS_NOTIFICATION_STYLE='ios_notification_style'
CONF_STRICT_USERS='strict_users'
CONF_ACCEPT_FIRST_SEEN_USERS='accept_first_seen_users'
CONF_ALLOWED_USERS='allowed_users'
CONF_ACTIVITY_FILTER='activity_filter'
CONF_UPDATE_INTERVAL='update_interval_seconds'
CONF_INITIAL_TRACKPOINT_WAIT='initial_trackpoint_wait_minutes'
CONF_MAX_RUNTIME_HOURS='max_runtime_hours'
CONF_STALE_MINUTES='stale_minutes'
CONF_FINALIZATION_MINUTES='finalization_minutes'
CONF_RETAIN_ENDED_HOURS='retain_ended_hours'
DEFAULT_LISTEN_TO_IMAP_EVENTS=True
DEFAULT_ENABLE_NOTIFICATIONS=True
DEFAULT_NOTIFY_SERVICE='notify.notify'
DEFAULT_IOS_NOTIFICATION_STYLE=False
DEFAULT_STRICT_USERS=False
DEFAULT_ACCEPT_FIRST_SEEN_USERS=False
DEFAULT_ALLOWED_USERS=[]
DEFAULT_ACTIVITY_FILTER='all'
DEFAULT_UPDATE_INTERVAL=timedelta(seconds=60)
DEFAULT_INITIAL_TRACKPOINT_WAIT=timedelta(minutes=10)
DEFAULT_MAX_RUNTIME_HOURS=23
DEFAULT_STALE_MINUTES=15
DEFAULT_FINALIZATION_MINUTES=10
DEFAULT_RETAIN_ENDED_HOURS=24
ACTIVITY_VALUES=['all','running','walking','cycling','strength','swimming','other']
STORAGE_KEY='garmin_livetrack.storage'
STORAGE_VERSION=1
RUNTIME_DATA='runtime_data'
