name: HACS
on:
  workflow_dispatch:
  push:
jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hacs/action@main
        with:
          category: integration
